version: '3.9'

volumes:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed

    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MbwNLSyhrn6ZbHMf #change this
      - MYSQL_PASSWORD=MbwNLSyhrn6ZbHMf #change this
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    build: .
    restart: always
    ports:
      - 8888:80
    links:
      - db
    volumes:
      - /home/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=MbwNLSyhrn6ZbHMf
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
